---
swagger: "2.0"
info:
  version: "2020-09-26T21:49:21Z"
  title: "pipeline-test"
schemes:
- "https"
paths:
  /demo:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambda-demo:${!stageVariables.lambdaAlias}/invocations"
        credentials:
          Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/${ApiGwLambdaRoleName}"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
